language: node_js
node_js: lts/*

env:
  global:
    - ENCRYPTION_LABEL="4190ff230232"

branches:
  only:
    - master

script:
  - shellcheck deploy.sh
  - npm run lint
  - npm test

after_success:
  - bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
